In [4]:
#1. Import numpy as np and see the version
import numpy as np
print(np.__version__)
#print(np.__config__)

1.16.4
<module 'numpy.__config__' from 'C:\\Users\\Venkata Sai\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


In [5]:
#2. How to create a 1D array?
from numpy import array
arr = array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [7]:
# 3. Q. Create a 1D array of numbers from 0 to 9
arr1 = np.arange(0,10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# 3. How to create a boolean array?
# Create a 3×3 numpy array of all True’s
arr2 = np.full((3,3), True, dtype = bool)
arr2


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
# Or
#3
    
arr3 = np.ones((3,3),dtype = bool)
print(arr3)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
# 4. How to extract items that satisfy a given condition from 1D array?
# Extract all odd numbers from arr
# arr4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr4 = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_result = arr4 % 2==1

print(arr4[odd_result])

array([1, 3, 5, 7, 9])

In [17]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
# Replace all odd numbers in arr with -1
# input ==> arr5 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr5 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr5[arr5%2==1]=-1
print(arr5)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [19]:
#6. How to replace items that satisfy a condition without affecting the original array?
# Replace all odd numbers in arr with -1 without changing arr
# arr6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr6 % 2 == 1, -1,arr6)
print(arr6)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [33]:
#7. How to reshape an array?
# Convert a 1D array to a 2D array with 2 rows
# input ==> arr7 = np.arange(10)
# we can use column value -1 or 5
arr7 = np.arange(10).reshape(2,-1)
arr7

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
#8. How to stack two arrays vertically?
# tack arrays a and b vertically
# input 1==> a = np.arange(10).reshape(2,-1)
# input 2==> b = np.repeat(1, 10).reshape(2,-1)
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)
print("--------------------- ")
print(a)
print()
print(b)
print("--------------------- ")

result = np.vstack([a,b])
print(result)
print()
result1 = np.concatenate([a, b], axis=0)
print(result)
np.r_[a, b]

--------------------- 
[[0 1 2 3 4]
 [5 6 7 8 9]]

[[1 1 1 1 1]
 [1 1 1 1 1]]
--------------------- 
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
# 9. How to stack two arrays horizontally?
# input1 a = np.arange(10).reshape(2,-1)
# input2 b = np.repeat(1, 10).reshape(2,-1)

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print("--------------------- ")
print(a)
print()
print(b)
print("--------------------- ")
print()
result1 = np.hstack([a,b])
print(result1)

print()
result2 = np.concatenate([a,b],axis=1)
print(result2)

np.c_[a,b]


--------------------- 
[[0 1 2 3 4]
 [5 6 7 8 9]]

[[1 1 1 1 1]
 [1 1 1 1 1]]
--------------------- 

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [46]:
#11. How to get the common items between two python numpy arrays?
#Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.intersect1d(a,b)
print(result)

[2 4]


In [50]:
#12. How to remove from one array those items that exist in another?
# From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a,b)
print(result)

[1 2 3 4]


In [53]:
#13. How to get the positions where elements of two arrays match?
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.where(a==b)
print(result)

(array([1, 3, 5, 7], dtype=int64),)


In [77]:
#14. How to extract all numbers between a given range from a numpy array?
#Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
result1 = a[(a>=5) & (a<=10)]
print(result)
print()
index = np.where(np.logical_and(a>=5 , a<=10))
print(a[index])
print()
index = np.where((a>=5) & (a<=10))
print(a[index])

[ 6  9 10]

[ 6  9 10]

[ 6  9 10]


In [79]:
#15. How to make a python function that handles scalars to work on numpy arrays?
# Q. Convert the function maxx that works on two scalars, to work on two arrays.
def max(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [84]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max= np.vectorize(max,otypes=[int])
print(pair_max(a,b))

[6 7 9 8 9 7 5]


In [85]:
#16. How to swap two columns in a 2d numpy array?
#Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
#swape coloumn 0 to 1 and i to 0
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [87]:
#17. How to swap two rows in a 2d numpy array?
#Swap rows 1 and 2 in the array arr:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
#swape row wise 1 to 2 and 2 to 1
arr[[0,2,1],:]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [93]:
#18. How to reverse the rows of a 2D array?
#Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [95]:
#19. How to reverse the columns of a 2D array?
#Reverse the columns of a 2D array arr.
# Input
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [100]:
#20. How to create a 2D array containing random floats between 5 and 10?
#Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
# solution
result_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(result_arr)
print()
result1_arr = np.random.uniform(5,10, size=(5,3))
print(result1_arr)

[[9.29673348 9.36408545 9.58449414]
 [5.05040347 7.07309186 8.8616145 ]
 [6.41532245 9.44685812 6.78297886]
 [5.52374038 5.51746018 9.44928383]
 [6.73375317 7.89236798 9.40121679]]

[[7.18928122 7.9445551  8.3855696 ]
 [9.88070111 6.84073158 7.2780236 ]
 [9.02353577 9.47687949 9.18822381]
 [9.64823998 8.87559104 8.67617707]
 [5.91158553 6.92270654 8.83186658]]


In [110]:
#21. How to print only 3 decimal places in python numpy array?
#Print or show only 3 decimal places of the numpy array rand_arr.
input_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
input_arr[:4]

array([[0.371, 0.485, 0.278],
       [0.192, 0.082, 0.843],
       [0.785, 0.969, 0.82 ],
       [0.091, 0.18 , 0.447]])

In [129]:
#22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
# Create the random array
np.random.seed(100)
np.set_printoptions(suppress=False)
input_random_arr = np.random.random([3,3])/1e3
print(input_random_arr)
print()
np.set_printoptions(suppress=True, precision=7)
print(input_random_arr)
print()

[[5.4340494e-04 2.7836939e-04 4.2451759e-04]
 [8.4477613e-04 4.7188562e-06 1.2156912e-04]
 [6.7074908e-04 8.2585276e-04 1.3670659e-04]]

[[0.0005434 0.0002784 0.0004245]
 [0.0008448 0.0000047 0.0001216]
 [0.0006707 0.0008259 0.0001367]]



In [139]:
#23. How to limit the number of items printed in output of numpy array?
#Limit the number of items printed in python numpy array a to a maximum of 6 elements.
input_arr = np.arange(16)
print(input_arr)
np.set_printoptions(suppress=False)
print()
#np.set_printoptions(threshold =6)
print(input_arr)

[ 0  1  2 ... 13 14 15]

[ 0  1  2 ... 13 14 15]


In [140]:
#24. How to print the full numpy array without truncating
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [152]:
import sys
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)
np.set_printoptions(threshold=sys.maxsize)
print(a)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [156]:
pwd

'C:\\Users\\Venkata Sai\\Desktop\\PYTHON\\Exercises\\Python\\Numpy'

In [167]:
#25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
import pandas as pd
input_path = 'C:\\Users\\Venkata Sai\\Desktop\\PYTHON\\Exercises\\Python\\Numpy'

df = pd.read_csv(input_path+'\\iris.data', names = ['A','B','C','D','E'])
df.head()


A    B    C    D            E
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [158]:
# or 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:2]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

In [171]:
#26. How to extract a particular column from 1D array of tuples?
#Extract the text column species from the 1D iris imported in previous question.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


C:\Users\Venkata Sai\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


array([(6., 3., 5., 2., b'Iris-virginica')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [174]:
series = np.array([row[4] for row in iris_1d])
series[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [182]:
#27. How to convert a 1d array of tuples to a 2d numpy array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
#test = np.genfromtxt(url, delimiter=',', dtype=None,max_rows=5) # display 5 rows
iris_2d = np.genfromtxt(url, delimiter=',', dtype =int,usecols=[0,1,2,3] )
iris_2d[:4]

C:\Users\Venkata Sai\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


array([[5, 3, 1, 0],
       [4, 3, 1, 0],
       [4, 3, 1, 0],
       [4, 3, 1, 0]])

In [199]:
#28. How to compute the mean, median, standard deviation of a numpy array?
#Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_data = np.genfromtxt(url,dtype=None,delimiter =',', usecols=[0])

iris_mean , iris_median,iris_std =np.mean(iris_data), np.median(iris_data), np.std(iris_data)
print('iris_mean= ',iris_mean,'iris_median= ',iris_median,'iris_std_diviation= ',iris_std)

iris_mean=  5.843333333333334 iris_median=  5.8 iris_std_diviation=  0.8253012917851409


In [210]:
#29. How to normalize an array so the values range exactly between 0 and 1?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_data = np.genfromtxt(url,dtype = float, delimiter = ',', usecols=[0])

iris_max, iris_min = iris_data.max(), iris_data.min()
print('iris_max = ',iris_max, 'iris_min= ',iris_min )

#normalize_data = (iris_data - iris_min) / (iris_max - iris_min)
normalize_data = (iris_data - iris_min) / iris_data.ptp()

print('Normalize data = ',normalize_data)


iris_max =  7.9 iris_min=  4.3
Normalize data =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0.
 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0.
 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 0.]


In [216]:
#30. How to compute the softmax score?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_data = np.genfromtxt(url, delimiter=',',dtype = float)
iris_len = np.array([float(row[0]) for row in iris_data])

def softmax(iris_len):
    e_value = np.exp(iris_len - np.max(iris_len))
    return e_value /e_value.sum(axis=0)
print(softmax(iris_len))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [219]:
#31. How to find the percentile scores of a numpy array?
#Find the 5th and 95th percentile of iris's data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_data = np.genfromtxt(url, delimiter = ',', dtype = float,usecols=[0])

np.percentile(iris_data,q=[5,95])

array([5., 7.])

In [234]:
#32. How to insert values at random positions in an array?
#Insert np.nan values at 20 random positions in iris_2d dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d_dataset = np.genfromtxt(url,delimiter=',',dtype = 'object')

print(iris_2d_dataset[:20])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']]


In [233]:
row_data, col_data = np.where(iris_2d_dataset)

np.random.seed(100)
iris_2d_dataset[np.random.choice((row_data), 20), np.random.choice((col_data), 20)] = np.nan
print(iris_2d_dataset[:20])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' nan b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' nan b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' nan b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' nan b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']]
