# NumPy Arrays

In [2]:
#one Dimentional Array
import numpy as np
list = [1,2,3,4]
arr = np.array(list)
arr


array([1, 2, 3, 4])

In [3]:
#Two dimentional Array
my_mat = [[1,2,3,4],[2,3,4,5],[3,4,5,6]]
arr1 =np.array(my_mat)
arr1


array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [5]:
# Range in Numpy
np.arange(0,10) #start , Stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2) #display all even numbers

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.arange(0,12,3) #display all even numbers

array([0, 3, 6, 9])

In [10]:
np.zeros([3,3]) # display the matrix 3 X 3 with all zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,3)) # display the matrix 3 X 3 with all ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(4) # display the matrix 4 X 4 with all ones and 1 will display in diangal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(4) #one dimential and display 4 random numbers

array([0.90610111, 0.76740803, 0.91352207, 0.17132072])

In [19]:
np.random.rand(3,3) display the matrix 3 X 3 with random numbers

array([[0.32502514, 0.33450104, 0.23566725],
       [0.21076348, 0.77600072, 0.14920744],
       [0.97863119, 0.98379007, 0.79718718]])

In [21]:
np.random.randint(1,10) # display one integer value between 1 and 10

5

In [23]:
np.random.randint(1,10,5) # display 5 integer values between 1 and 10

array([3, 1, 6, 2, 2])

In [37]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr.max()


24

In [41]:
arr.min()

0

In [43]:
arr.argmax()

24

In [44]:
arr.argmin()

0

In [45]:
arr.shape

(25,)

In [50]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr.shape

(25,)

In [56]:
from numpy.random import randint
randint(2,10)

2

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [59]:
arr[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [60]:
arr[:-3]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [61]:
arr[-1]

24

In [70]:
arr[-3:]

array([22, 23, 24])

In [64]:
arr[:3-]

SyntaxError: invalid syntax (<ipython-input-64-c4a7248097d9>, line 1)

In [65]:
test_list = [1, 4, 5, 6, 3, 5] 
test_list[-1]

5

In [68]:
test_list[-3:]

[6, 3, 5]

In [71]:
# Numpy indexing and selection
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
slicing_arr = arr[2:5]
slicing_arr

array([2, 3, 4])

In [76]:
import numpy as np
arr_2d = np.array([[1,2,3],[2,3,4],[3,4,5]])
arr_2d

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [78]:
arr_2d[2][2]

5

In [79]:
arr_2d[1,2]

4

In [80]:
arr_2d

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [85]:
arr_2d[:2,1:]

array([[2, 3],
       [3, 4]])

In [92]:
arr_2d[:3,1:]

array([[2, 3],
       [3, 4],
       [4, 5]])

In [94]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [96]:
boolean_arr = arr>5 # display TRUE from 6 to end number
boolean_arr

array([False, False, False, False, False,  True,  True,  True,  True])

In [97]:
arr[boolean_arr] # display all the number who are TRUE

array([6, 7, 8, 9])

In [99]:
arr[arr>5]

array([6, 7, 8, 9])

In [100]:
arr_2d = np.arange(50).reshape(5,10)

In [101]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [123]:
arr_2d[2:5,2:5]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

# Numpy Operations
Array with Array
Aray With Scalers
Universal Array Functions


In [125]:
arr = np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [126]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [127]:
arr-arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [128]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [129]:
arr *10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [130]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [186]:
import numpy as np
arr =np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [187]:
arr+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [132]:
arr_0 = np.ones(10)
arr_0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [133]:
arr_arange = np.arange(10,50)
arr_arange

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [134]:
arr_arange_even = np.arange(10,50,2)
arr_arange_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [135]:
arr_mat = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr_mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [136]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
import numpy as np

np.random.rand(1)


array([0.09507179])

In [148]:
np.random.rand(25)

array([0.41857374, 0.30740952, 0.39680079, 0.48653064, 0.29522792,
       0.50286725, 0.14798068, 0.60521655, 0.14979416, 0.99682377,
       0.37270145, 0.30457705, 0.7522007 , 0.86886657, 0.90913444,
       0.31459117, 0.14331511, 0.16214445, 0.00797367, 0.21568793,
       0.97472071, 0.57619788, 0.74327084, 0.4998016 , 0.38818255])

In [149]:
np.random.rand(10,10)

array([[0.53911908, 0.85116148, 0.62906707, 0.51410552, 0.6220785 ,
        0.48537123, 0.71824739, 0.43453374, 0.24047437, 0.5248844 ],
       [0.67899095, 0.91969499, 0.16083445, 0.62886398, 0.29483152,
        0.6155658 , 0.15018004, 0.69899979, 0.63866468, 0.23521774],
       [0.87786679, 0.98826002, 0.16150462, 0.78285515, 0.25704211,
        0.29563611, 0.8724629 , 0.80866206, 0.15464834, 0.83979638],
       [0.03798451, 0.24167254, 0.64529609, 0.46700775, 0.98401333,
        0.46956919, 0.36469626, 0.36988036, 0.19192494, 0.05574165],
       [0.40240905, 0.30215729, 0.69095729, 0.12061542, 0.14615629,
        0.9113653 , 0.31310819, 0.87614301, 0.30584311, 0.80927823],
       [0.62790054, 0.18265656, 0.5305872 , 0.14412789, 0.94491743,
        0.1603132 , 0.40712026, 0.15178069, 0.70801967, 0.67122996],
       [0.22915403, 0.45947952, 0.00462255, 0.26121331, 0.12861422,
        0.84709602, 0.29528791, 0.13376713, 0.7438402 , 0.41824117],
       [0.35271309, 0.31640646, 0.6940182

In [150]:
np.random.rand(100)

array([0.71737855, 0.68763106, 0.36067355, 0.87985977, 0.27444462,
       0.06234648, 0.24781092, 0.07120993, 0.99633803, 0.04368957,
       0.16706196, 0.02217006, 0.76104534, 0.46527557, 0.16367178,
       0.56788258, 0.82334043, 0.69528964, 0.92851118, 0.73996147,
       0.50226828, 0.0636283 , 0.85051188, 0.47591866, 0.20520377,
       0.35462329, 0.75625706, 0.72957817, 0.36023983, 0.22295199,
       0.64281491, 0.58804661, 0.69369129, 0.50252441, 0.67190541,
       0.64505484, 0.92685676, 0.81312033, 0.97440786, 0.18024796,
       0.14057984, 0.48257565, 0.54911024, 0.42783589, 0.99100872,
       0.07969337, 0.04069036, 0.74219909, 0.08108218, 0.75790479,
       0.47995219, 0.79111598, 0.44290209, 0.57711128, 0.73458137,
       0.85561791, 0.15173656, 0.65874859, 0.64927262, 0.01469319,
       0.50087593, 0.40393665, 0.53048208, 0.27351852, 0.44862334,
       0.8352087 , 0.28767839, 0.47997056, 0.33756372, 0.55002332,
       0.93558324, 0.02134014, 0.70484137, 0.34527664, 0.03377

In [153]:
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [165]:
arr[2:5,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [168]:
arr[3,4]

20

In [172]:
arr[0:3,1]

array([ 2,  7, 12])

In [174]:
arr[4]

array([21, 22, 23, 24, 25])

In [178]:
arr[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [179]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [180]:
np.sum(arr)

325

In [183]:
np.std(arr)

7.211102550927978

In [184]:
np.sum(arr, axis=0)

array([55, 60, 65, 70, 75])

In [189]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [190]:
arr.std()

7.211102550927978

In [191]:
arr.sum()

325