# Numpy is the core library in python for calculating the scientific calculations. It Provides a high performance multi dimentional array object


In [76]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([[2,3,4,5],[4,5,6,6]])
c = np.array([(3,4,6),(1,2,3)], dtype=int)
d = np.array([[(1,2,3),(3,4,5)],[(3,4,5),(9,8,7)]],dtype = float)
d

array([[[1., 2., 3.],
        [3., 4., 5.]],

       [[3., 4., 5.],
        [9., 8., 7.]]])

In [3]:
b.dtype

dtype('O')

In [19]:
#Creating an array of zeros by defualt it will display float
np.zeros([3,4],dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
#Creating an array of ones by defualt it will display float
np.ones((3,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
#Creating an array of ones of 2 arrays with 3 rows and 5 columns by defualt it will display float
np.ones((2,3,5),dtype =int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [28]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [30]:
#display an array of between numbers
d = np.arange(10,25)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
#display an array of between numbers and spaced values (step value) by 5
arr = np.arange(10,25,5)
arr

array([10, 15, 20])

In [33]:
arr = np.arange(10,25,2)

In [34]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24])

In [35]:
arr = np.arange(10,25,3)

In [36]:
arr

array([10, 13, 16, 19, 22])

In [39]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [40]:
#Create a constant array
e = np.full((2,2),7)

In [41]:
e

array([[7, 7],
       [7, 7]])

In [43]:
f = np.eye(2,dtype = int)
f

array([[1, 0],
       [0, 1]])

In [47]:
np.random.random((2,2))

array([[0.40443857, 0.17283873],
       [0.00726436, 0.77944329]])

In [58]:
np.random.rand(2,2)

array([[0.33778821, 0.04308045],
       [0.25835914, 0.27189561]])

In [53]:
np.empty((2,3),dtype = int)

array([[-1431655765,  1073392298, -1431655765],
       [ 1074440874,           0,  1075052544]])

In [59]:
np.save('my_array', d)

In [60]:
np.savez('array.npz', b, c)

In [62]:
np.load('my_array.npy')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

Inspecting Your Array

In [73]:
len(b)
d.ndim
d.dtype.name

'int32'

In [74]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


Arithmetic Operations

In [78]:
a


array([1, 2, 3, 4])

In [79]:
b

array([[2, 3, 4, 5],
       [4, 5, 6, 6]])

In [81]:
add = a+b
add

array([[ 3,  5,  7,  9],
       [ 5,  7,  9, 10]])

In [83]:
sub = b-a
sub

array([[1, 1, 1, 1],
       [3, 3, 3, 2]])

In [84]:
np.multiply(a,b)

array([[ 2,  6, 12, 20],
       [ 4, 10, 18, 24]])

In [85]:
np.exp(b)

array([[  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ],
       [ 54.59815003, 148.4131591 , 403.42879349, 403.42879349]])

In [86]:
np.sqrt(b)

array([[1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.        , 2.23606798, 2.44948974, 2.44948974]])

In [87]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [88]:
a.sum()

10

In [89]:
b.sum()

35

In [90]:
b.min()

2

In [91]:
b.max()

6

In [93]:
b.mean()

4.375

In [95]:
b.sort()

In [96]:
b

array([[2, 3, 4, 5],
       [4, 5, 6, 6]])

In [102]:
a.corrcoef()


AttributeError: 'numpy.ndarray' object has no attribute 'corrcoef'

In [99]:
b.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [103]:
c

array([[3, 4, 6],
       [1, 2, 3]])

In [104]:
d

array([[[1., 2., 3.],
        [3., 4., 5.]],

       [[3., 4., 5.],
        [9., 8., 7.]]])

In [105]:
c

array([[3, 4, 6],
       [1, 2, 3]])

In [106]:
b

array([[2, 3, 4, 5],
       [4, 5, 6, 6]])

In [107]:
c

array([[3, 4, 6],
       [1, 2, 3]])

In [109]:
c.sort(axis=0)

In [110]:
c

array([[1, 2, 3],
       [3, 4, 6]])

In [112]:
b1= np.array([[11,2,38],[8,6,3],[9,2,13]])
b1

array([[11,  2, 38],
       [ 8,  6,  3],
       [ 9,  2, 13]])

In [113]:
b1.sort(axis=0)

In [114]:
b1

array([[ 8,  2,  3],
       [ 9,  2, 13],
       [11,  6, 38]])

In [115]:
b1.sort(axis =1)

In [116]:
b1

array([[ 2,  3,  8],
       [ 2,  9, 13],
       [ 6, 11, 38]])

In [118]:
b1[1][2]

13

In [8]:
import numpy as np
arr =np.array(([1,2,3,4],[4,5,6,7]))
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [9]:
arr[:,2]

array([3, 6])

In [10]:
arr[1,2]

6

In [12]:
arr[1,:2]

array([4, 5])

In [13]:
a =np.array([4,5,6,7])
a

array([4, 5, 6, 7])

In [16]:
a[:3]

array([4, 5, 6])

In [22]:
b = np.random.random((1,9,1))
np.mean(b)

0.3966980772818907

In [23]:
b.sort().median()

AttributeError: 'NoneType' object has no attribute 'median'

In [24]:
b.sort()

In [34]:
c = np.random.randint(0,9,9)
c.sort()
c

array([0, 1, 3, 4, 6, 6, 6, 7, 8])

In [35]:
c.mean()

4.555555555555555

In [36]:
c.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [37]:
np.median(c)

6.0

In [38]:
np.mode(c)

AttributeError: module 'numpy' has no attribute 'mode'

In [39]:
c.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [40]:
np.std(c)

2.5867659392939593

In [41]:
c.max()

8

In [42]:
c.min()

0